Update security.md
OAI/learn.openapis.org pull request #110
Opened 2024-10-03 17:02 UTC by darrelmiller

Fix security examples as the security property is an array.

2024-10-03 19:55 UTC, kevinswiber commented
@darrelmiller I think this also needs to be fixed on lines 58, 142, and 188.

2024-10-03 20:23 UTC, kevinswiber requested changes
@darrelmiller Just one little hiccup. Otherwise, LGTM!

2024-10-03 20:23 UTC, kevinswiber commented on specification/security.md
> +      - security:
@darrelmiller This hyphen needs to be removed.

2024-10-03 21:58 UTC, karenetheridge commented
"defaultApiKey" is not one of the valid entries for a securityScheme. The schema currently only allows for one of: apiKey, http, mutualTLS, oauth2, openIdConnect.

2024-10-03 22:49 UTC, kevinswiber commented
> "defaultApiKey" is not one of the valid entries for a securityScheme. The schema currently only allows for one of: apiKey, http, mutualTLS, oauth2, openIdConnect.

@karenetheridge I believe this is the `name` in the Security Requirement Object, which must correspond to a name in `#/components/securitySchemes`. The example shows a Security Scheme Object in Components that's called `defaultApiKey`, so I think this might be correct.

2024-10-04 03:20 UTC, karenetheridge commented
Aha, my confusion came from "The name used for each property MUST correspond to a security scheme declared in the [Security Schemes](https://spec.openapis.org/oas/v3.1.0#componentsSecuritySchemes) under the [Components Object](https://spec.openapis.org/oas/v3.1.0#components-object)." -- which I interpreted as the `type`, not the property name under components.

2024-10-04 03:38 UTC, handrews commented
@karenetheridge 

> Aha, my confusion came from "The name used for each property MUST correspond to a security scheme declared in the [Security Schemes](https://spec.openapis.org/oas/v3.1.0#componentsSecuritySchemes) under the [Components Object](https://spec.openapis.org/oas/v3.1.0#components-object)." -- which I interpreted as the type, not the property name under components.

Ah, good catch.  The wording could perhaps be something like "The name used for each property MUST correspond to the name of a property under the `securitySchemes` field of the Components Object."

2024-10-08 09:56 UTC, ralfhandl commented on specification/security.md
> +      - security:
```suggestion
      security:
```

2024-10-08 10:02 UTC, ralfhandl approved these changes

2024-10-08 11:01 UTC, mikekistler approved these changes
Looks good. 👍

2024-10-08 11:10 UTC, merged