minor fixes
OAI/learn.openapis.org pull request #63
Opened 2023-09-25 14:07 UTC by dret

2023-11-22 08:42 UTC, lornajane requested changes
Thanks! Can you update the examples title so it's more vague please?

2023-11-22 08:42 UTC, lornajane commented on specification/docs.md
> +## The Examples Object
Maybe we should name this section "Adding Examples" to avoid being specific about `example` or `examples`. The text makes it pretty clear.

2023-11-22 08:55 UTC, dret commented
I think I made the requested change, @lornajane.

2023-12-14 14:57 UTC, darrelmiller approved these changes

2023-12-14 14:57 UTC, merged